require("config.options")
require("config.lazy")
require("config.lsp")
require("config.terminal")
require("config.maps")
require("luasnip.loaders.from_lua").lazy_load({ paths = "~/.config/nvim/luaSnip/" })
